import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const iBM_Plex_Sans_Thai =  IBM_Plex_Sans_Thai(
  { 
    weight: ['400','500','600', '700'],
    style: ['normal'],
    subsets: ['latin'],
    display: 'swap',
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbar =[
  {title:'Home',href:'/',status:'on'},
  {title:'Products',href:'#',status:'on'},
  {title:'projects',href:'#',status:'on'},
  {title:'About us',href:'#',status:'on'},
  {title:'Blog',href:'#',status:'on'},
  {title:'Contact',href:'#',status:'on'},
]

export default function RootLayout({ children }) {
  return (
    <html className={iBM_Plex_Sans_Thai.className}>
      <body className="block">
        <Navbar data={navbar}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
